# Generated by Django 4.1.2 on 2022-11-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0002_rename_update_date_cupon_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cupon.shop'),
        ),
    ]
