# Generated by Django 4.1.2 on 2022-12-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0003_alter_cupon_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
