# Generated by Django 4.1.2 on 2022-11-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('giro', models.CharField(max_length=200)),
                ('confirmation', models.BooleanField(default=False)),
                ('comision', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=200)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('comision_date', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('long', models.IntegerField()),
                ('price', models.IntegerField()),
                ('folder', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('status_payment', models.BooleanField(default=False)),
                ('status_sale', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.sale')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupon.shop')),
            ],
        ),
    ]
