# Generated by Django 4.1.2 on 2022-12-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='service',
            name='regular_price',
            field=models.IntegerField(default=100),
        ),
    ]
