# Generated by Django 3.2.18 on 2023-03-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('money_release_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_amount', models.IntegerField(blank=True, null=True)),
                ('transaction_amount_refunded', models.IntegerField(blank=True, null=True)),
                ('coupon_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'index_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexCartdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'index_cartdetail',
                'managed': False,
            },
        ),
    ]
