# Generated by Django 4.1.2 on 2023-02-12 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0005_level_userdetail_level'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('money_release_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_amount', models.IntegerField(blank=True, null=True)),
                ('transaction_amount_refunded', models.IntegerField(blank=True, null=True)),
                ('coupon_amount', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.service')),
            ],
        ),
    ]
