# Generated by Django 4.1.2 on 2023-01-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
