# Generated by Django 3.2.18 on 2023-03-02 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_level_userdetail_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 21, 51, 4, 631502, tzinfo=utc)),
        ),
    ]
