# Generated by Django 4.2 on 2023-05-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_alter_account_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
