"""
Django settings for CuentasMexico project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# django
from django.urls import reverse_lazy

# python
from pathlib import Path
import os
from dotenv import load_dotenv

# Token para acceso a iframe de ventas (debe cambiarse en producción)
IFRAME_ACCESS_TOKEN = os.environ.get('IFRAME_ACCESS_TOKEN', '7145fd4e-9f73-44e2-b733-8a18fb2bb377')


import pymysql
pymysql.version_info = (1, 4, 5, "final", 0)  # Ajusta la versión según la que tengas instalada
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uf41q9_1%4#x4!k4a)pa#pqc&5aj^-s)*f5lcicaui-$m2@s*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS desde variable de entorno (separados por coma)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF_TRUSTED_ORIGINS desde variable de entorno (separados por coma)
# Debe incluir el protocolo (https:// o http://)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    "whitenoise.runserver_nostatic",
    'storages',  # django-storages para S3/Backblaze
    'adm',
    'index',
    'cupon',
    'api',
    'corsheaders',
    'api_bot',
    'ThanksYou'
]
INSTALLED_APPS += ('naomi',)
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'CuentasMexico.middleware.RemoveXFrameOptionsMiddleware',  # Nuestro nuevo middleware
    'adm.middleware.PageVisitMiddleware',  # Middleware para rastrear visitas
]

# Configuración de login para permitir iframe
LOGIN_REDIRECT_URL = '/adm/sales'
LOGIN_URL = '/login'
LOGOUT_REDIRECT_URL = '/login'

# Configuración de CORS desde variables de entorno
CORS_ALLOW_CREDENTIALS = True
# Si CORS_ALLOWED_ORIGINS está vacío o es '*', permite todos los orígenes
_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '*')
if _cors_origins == '*' or not _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _cors_origins.split(',')

ROOT_URLCONF = 'CuentasMexico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'index.context_processors.affiliate_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'CuentasMexico.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# mysql://root:NbsAjgXbGdaGmXuAritURIPcORuXpdQY@roundhouse.proxy.rlwy.net:55263/railway

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cuentasmexico',
#         'USER': 'cuentasmexico',
#         'PASSWORD': 'Tarkan11.-',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Configuración de Backblaze B2 via S3 Compatible API
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-west-002')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', '')
AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', '')

# Configuración adicional de S3
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False  # URLs públicas sin firma
AWS_S3_SIGNATURE_VERSION = 's3v4'

# Storage backend para archivos (usará Backblaze B2 via S3)
if all([AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME, AWS_S3_ENDPOINT_URL]):
    DEFAULT_FILE_STORAGE = 'adm.functions.backblaze.BackblazeS3Storage'
else:
    import warnings
    warnings.warn(
        "Backblaze B2 (S3) no está completamente configurado. "
        "Se usará almacenamiento local. "
        "Configura: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME, AWS_S3_ENDPOINT_URL"
    )

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = reverse_lazy("redirect_on_login")
LOGOUT_REDIRECT_URL = reverse_lazy("login")
LOGIN_URL = reverse_lazy("login")
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'

DATE_INPUT_FORMATS = ('%d-%m-%Y')

# WhatsApp API Configuration
# Evolution API Configuration for WhatsApp
EVO_WHATSAPP_API_URL = os.getenv('EVO_WHATSAPP_API_URL', '')
EVO_INSTANCE = os.getenv('EVO_INSTANCE', '')
EVO_API_KEY = os.getenv('EVO_API_KEY', '')

# EMAIL_BACKEND = "naomi.mail.backends.naomi.NaomiBackend"
# EMAIL_FILE_PATH = "/Users/luinmack/Documents/Proyectos/CuentasMexico/tmp"

# Configuración de sesiones para permitir múltiples sesiones concurrentes
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 604800 * 4  # 7 días (una semana)
SESSION_COOKIE_SECURE = DEBUG 
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Configuración de caché para mejorar rendimiento
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 600,  # 10 minutos por defecto
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'webhook_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'webhook.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'sync_sheets_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'sync_sheets.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'index.views': {
            'handlers': ['console', 'webhook_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'adm.functions.sync_google_sheets': {
            'handlers': ['console', 'sync_sheets_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
